repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.1.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-merge-conflict
        -   id: check-case-conflict
        -   id: name-tests-test
        -   id: requirements-txt-fixer
            # args: [--max-line-length=90]

    -   repo: https://github.com/psf/black
        rev: 19.10b0
        hooks:
        -   id: black
            language_version: python3.8

    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
        -   id: flake8
            language_version: python3.8

default_stages: [commit,push]
