version: '3.4'

services:
  tango:
    container_name: tango
    image: elment/tango
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: >
      sh -c "python3 src/run.py"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
